# Site settings
title: "@speakingcode"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Developer site for @speakingcode. Programming tips & tricks, code snippets, hacks and other computer funs...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: speakingcode
github_username:  speakingcode

# Build settings
markdown: kramdown
